---
title: "Alberto charts"
author: "www.databrew.cc"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: "hide"
---


```{r setup, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               # echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.width = 8.64,
               fig.height = 4.86,
               fig.path = 'figures/')
```

```{r}
## Load libraries
library(covid19)
library(ggplot2)
library(lubridate)
library(dplyr)
library(ggplot2)
ylog <- FALSE
options(scipen = '999')
```


## Linear-scale charts

### Cumulative cases (absolute)

```{r}
text_size <- 20
pd <- df %>% filter(country == 'Spain')
pd <- pd %>% left_join(world_pop)
pd$value <- pd$confirmed_cases
pd <- pd %>% filter(value > 0)
pd <- pd %>% group_by(country, date) %>%
  summarise(value = sum(value, na.rm = TRUE))

g1 <- ggplot(data = pd,
       aes(x = date,
           y = value)) +
  theme_simple() +
  geom_line() +
  geom_point() +
  labs(x = 'Date',
       y = 'Cases',
       title = 'Spain: Confirmed COVID-19 cases',
       subtitle = paste0('Data as of ', max(pd$date))) +
  theme(axis.title = element_text(size = text_size),
        axis.text = element_text(size = text_size)) +
  geom_text(data = pd %>% filter(date == max(date)),
            aes(x = date - 3,
                y = value,
                label = scales::comma(round(value, digits = 1))),
            alpha = 0.7)
if(ylog){
  g1 <- g1 +
    scale_y_log10()
}
g1
```

Comparison with Italy


```{r}
text_size <- 20
pd <- df %>% filter(country %in% c('Italy', 'Spain'))
pd <- pd %>% left_join(world_pop)
pd$value <- pd$confirmed_cases
pd <- pd %>% filter(value > 0)
pd <- pd %>% group_by(country, date) %>%
  summarise(value = sum(value, na.rm = TRUE))
g1x <- ggplot(data = pd,
       aes(x = date,
           y = value)) +
  theme_simple() +
  geom_line(aes(color = country)) +
  geom_point(aes(color = country)) +
  labs(x = 'Date',
       y = 'Cases',
       title = 'Spain: Confirmed COVID-19 cases',
       subtitle = paste0('Data as of ', max(pd$date))) +
  theme(axis.title = element_text(size = text_size),
        axis.text = element_text(size = text_size)) +
  geom_text(data = pd %>% filter(date == max(date)),
            aes(x = date - 3,
                y = value,
                color = country,
                label = round(value, digits = 1)),
            alpha = 0.7) +
  scale_color_manual(name = '', values = c('red', 'black'))
if(ylog){
  g1x <- g1x + scale_y_log10()
}
g1x
```




### Cumulative deaths (absolute)

```{r}
text_size <- 20

pd <- df %>% filter(country == 'Spain')
pd <- pd %>% left_join(world_pop)
pd$value <- pd$deaths 
pd <- pd %>% filter(value > 0)
pd <- pd %>% group_by(country, date) %>%
  summarise(value = sum(value, na.rm = TRUE))

g2 <- ggplot(data = pd,
       aes(x = date,
           y = value)) +
  theme_simple() +
  geom_line() +
  geom_point() +
  labs(x = 'Date',
       y = 'Deaths',
       title = 'Spain: Confirmed COVID-19 deaths',
       subtitle = paste0('Data as of ', max(pd$date))) +
  theme(axis.title = element_text(size = text_size),
        axis.text = element_text(size = text_size)) +
  geom_text(data = pd %>% filter(date == max(date)),
            aes(x = date,
                y = value - ifelse(ylog, 1000, 300),
                label = round(value, digits = 1)),
            alpha = 0.7)
if(ylog){
  g2 <- g2 + scale_y_log10()
}
g2
```



Comparison with Italy


```{r}
text_size <- 20
pd <- df %>% filter(country %in% c('Italy', 'Spain'))
pd <- pd %>% left_join(world_pop)
pd$value <- pd$deaths
pd <- pd %>% filter(value > 0)
pd <- pd %>% group_by(country, date) %>%
  summarise(value = sum(value, na.rm = TRUE))


g2x <- ggplot(data = pd,
       aes(x = date,
           y = value)) +
  theme_simple() +
  geom_line(aes(color = country)) +
  geom_point(aes(color = country)) +
  labs(x = 'Date',
       y = 'Deaths',
       title = 'Spain: Confirmed COVID-19 deaths',
       subtitle = paste0('Data as of ', max(pd$date))) +
  theme(axis.title = element_text(size = text_size),
        axis.text = element_text(size = text_size)) +
  geom_text(data = pd %>% filter(date == max(date)),
            aes(x = date - 2,
                y = value,
                label = round(value, digits = 1)),
            alpha = 0.7) +
  scale_color_manual(name = '', values = c('red', 'black'))
if(ylog){
  g2x <- g2x + scale_y_log10()
}
g2x
```


### Cumulative cases by population

```{r}
text_size <- 20

pd <- df %>% filter(country == 'Spain')
pd <- pd %>% left_join(world_pop)
pd$value <- pd$confirmed_cases / pd$pop * 100000
pd <- pd %>% filter(value > 0)
pd <- pd %>% group_by(country, date) %>%
  summarise(value = sum(value, na.rm = TRUE))

g3 <- ggplot(data = pd,
       aes(x = date,
           y = value)) +
  theme_simple() +
  geom_line() +
  geom_point() +
  labs(x = 'Date',
       y = 'Cases (per 100,000)',
       title = 'Spain: Confirmed COVID-19 cases per 100,000 population',
       subtitle = paste0('Data as of ', max(pd$date))) +
  theme(axis.title = element_text(size = text_size),
        axis.text = element_text(size = text_size)) +
  geom_text(data = pd %>% filter(date == max(date)),
            aes(x = date,
                y = value - ifelse(ylog, 40, 10),
                label = round(value, digits = 1)),
            alpha = 0.7)
if(ylog){
  g3 <- g3 + scale_y_log10()
}
g3
```

Comparison with Italy


```{r}
text_size <- 20

pd <- df %>% filter(country %in% c('Spain', 'Italy'))
pd <- pd %>% left_join(world_pop)
pd$value <- pd$confirmed_cases / pd$pop * 100000
pd <- pd %>% filter(value > 0)
pd <- pd %>% group_by(country, date) %>%
  summarise(value = sum(value, na.rm = TRUE))

g3x <- ggplot(data = pd,
       aes(x = date,
           y = value)) +
  theme_simple() +
  geom_line(aes(color = country)) +
  geom_point(aes(color = country)) +
  labs(x = 'Date',
       y = 'Cases (per 100,000)',
       title = 'Spain: Confirmed COVID-19 cases per 100,000 population',
       subtitle = paste0('Data as of ', max(pd$date))) +
  theme(axis.title = element_text(size = text_size),
        axis.text = element_text(size = text_size)) +
  geom_text(data = pd %>% filter(date == max(date)),
            aes(x = date +2,
                y = value,
                label = round(value, digits = 1)),
            alpha = 0.7) +
  scale_color_manual(name ='',
                     values = c('red', 'black'))

if(ylog){
  g3x <- g3x + scale_y_log10()
}
g3x
```




### Cumulative deaths by population

```{r}
text_size <- 20

pd <- df %>% filter(country == 'Spain')
pd <- pd %>% left_join(world_pop)
pd$value <- pd$deaths / pd$pop * 100000
pd <- pd %>% filter(value > 0)
pd <- pd %>% group_by(country, date) %>%
  summarise(value = sum(value, na.rm = TRUE))

g4 <- ggplot(data = pd,
       aes(x = date,
           y = value)) +
  theme_simple() +
  geom_line() +
  geom_point() +
  labs(x = 'Date',
       y = 'Mortality rate (per 100,000)',
       title = 'Spain: Confirmed COVID-19 deaths per 100,000 population',
       subtitle = paste0('Data as of ', max(pd$date))) +
  theme(axis.title = element_text(size = text_size),
        axis.text = element_text(size = text_size)) +
  geom_text(data = pd %>% filter(date == max(date)),
            aes(x = date -1,
                y = value,
                label = round(value, digits = 1)),
            alpha = 0.7)

if(ylog){
  g4 <- g4 + scale_y_log10()
}
g4
```

Comparison with Italy

```{r}
text_size <- 20

pd <- df %>% filter(country %in% c('Spain', 'Italy'))
pd <- pd %>% left_join(world_pop)
pd$value <- pd$deaths / pd$pop * 100000
pd <- pd %>% filter(value > 0)
pd <- pd %>% group_by(country, date) %>%
  summarise(value = sum(value, na.rm = TRUE))

g4x <- ggplot(data = pd,
       aes(x = date,
           y = value)) +
  theme_simple() +
  geom_line(aes(color = country)) +
  geom_point(aes(color = country)) +
  labs(x = 'Date',
       y = 'Mortality rate (per 100,000)',
       title = 'Spain: Confirmed COVID-19 deaths per 100,000 population',
       subtitle = paste0('Data as of ', max(pd$date))) +
  theme(axis.title = element_text(size = text_size),
        axis.text = element_text(size = text_size)) +
  geom_text(data = pd %>% filter(date == max(date)),
            aes(x = date -1,
                y = value,
                label = round(value, digits = 1)),
            alpha = 0.7) +
  scale_color_manual(name ='', values = c('red', 'black') )
if(ylog){
  g4x <- g4x + scale_y_log10()
}
g4x
```


# Italy only UCI charts


```{r, fig.height = 9, fig.width = 12}
pdf('~/Desktop/alberto1.pdf',
    height = 9, 
    width = 12)
small_text_size = 9
Rmisc::multiplot(g1 + theme(axis.title = element_text(size = small_text_size),
        axis.text = element_text(size = small_text_size), plot.title = element_text(size = small_text_size * 1.4)), 
        g2  + theme(axis.title = element_text(size = small_text_size),
        axis.text = element_text(size = small_text_size), plot.title = element_text(size = small_text_size * 1.4)), 
        g3  + theme(axis.title = element_text(size = small_text_size),
        axis.text = element_text(size = small_text_size), plot.title = element_text(size = small_text_size * 1.4)), 
        g4  + theme(axis.title = element_text(size = small_text_size),
        axis.text = element_text(size = small_text_size), plot.title = element_text(size = small_text_size * 1.4)),
                 cols = 2) 
dev.off()
```


```{r, fig.height = 9, fig.width = 12}
pdf('~/Desktop/alberto1_with_italy.pdf',
    height = 9, 
    width = 12)
small_text_size = 9
Rmisc::multiplot(g1x + theme(axis.title = element_text(size = small_text_size),
        axis.text = element_text(size = small_text_size), plot.title = element_text(size = small_text_size * 1.4)), 
        g2x  + theme(axis.title = element_text(size = small_text_size),
        axis.text = element_text(size = small_text_size), plot.title = element_text(size = small_text_size * 1.4)), 
        g3x  + theme(axis.title = element_text(size = small_text_size),
        axis.text = element_text(size = small_text_size), plot.title = element_text(size = small_text_size * 1.4)), 
        g4x  + theme(axis.title = element_text(size = small_text_size),
        axis.text = element_text(size = small_text_size), plot.title = element_text(size = small_text_size * 1.4)),
                 cols = 2) 
dev.off()
```

